# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Mdoq
email: sales@mdoq.io
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://docs.mdoq.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  jekyll
error_mode: strict
mdoq_ip: 91.121.169.206
# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# social stuff
twitter_username: MDOQ_UK
youtube:
  username: MDOQ
  url: channel/UCfxjy1fBuE09r2XuVet3kaQ/featured

# footer stuff
footer:
  copyright: "© 2018 ZERO-1 Limited. MDOQ is a trade mark of ZERO-1 Registered in England No 03837629 | Registered address: West Road House, West Road, Buxton, United Kingdom, SK17 6HF"